import { Stock } from "../../../types/Stock";
import { isEarningsStable, isDividendStable, hasEarningsIncreased, threeYearsPeRatio, priceToAssetRatio, goodForDefensiveInvestor, goodForEnterprisingInvestor } from "./benjaminGrahamUtils";

export const getDefensiveData = (stockData: Stock) => ({
    "Revenue": {
      value: (parseFloat(stockData.detail?.totalRevenue ?? "0")/1000000000).toFixed(2) + " B",
      description: "Revenue refers to the total income generated by the company from its business activities.",
      color: parseFloat(stockData.detail?.totalRevenue ?? "0") >= 100000000 ? "green" : "red",
    },
    "Current Ratio": {
      value: stockData.detail?.currentRatio ?? "N/A",
      description: "The current ratio measures the company's current assets against its current liabilities.",
      color: parseFloat(stockData.detail?.currentRatio ?? "0") >= 2 ? "green" : "red",
    },
    "Earnings Stability": {
      value: isEarningsStable(stockData.eps, 10) ? "Stable" : "Unstable",
      description: "This indicates whether the company's earnings per share have remained positive over the last 10 years.",
      color: isEarningsStable(stockData.eps, 10) ? "green" : "red",
    },
    "Dividend Record": {
      value: isDividendStable(stockData.dividends, 20) ? "Stable" : "Unstable",
      description: "A stable dividend record means the company has consistently paid dividends over the last 20 years.",
      color: isDividendStable(stockData.dividends, 20) ? "green" : "red",
    },
    "Earnings Growth": {
      value: hasEarningsIncreased(stockData.eps, "defensive") !== -1 ? hasEarningsIncreased(stockData.eps, "defensive").toFixed(2) : "N/A",
      description: "The average growth of earnings per share in the past ten years using three-year averages.",
      color: hasEarningsIncreased(stockData.eps, "defensive") >= 4.0/3 ? "green" : "red",
    },
    "Price/Earnings Ratio": {
      value: threeYearsPeRatio(stockData.peRatio).toFixed(2),
      description: "The current price against the average earnings per share over the last three years.",
      color: threeYearsPeRatio(stockData.peRatio) <= 15.0 ? "green" : "red",
    },
    "Price/Assets Ratio": {
      value: priceToAssetRatio(stockData.peRatio, stockData.detail?.priceToBook || Infinity.toString()) !== Infinity ? priceToAssetRatio(stockData.peRatio, stockData.detail?.priceToBook || Infinity.toString()).toFixed(2) : "N/A",
      description: "This measures the ratio of the stock price to the book value of the company's assets.",
      color: priceToAssetRatio(stockData.peRatio, stockData.detail?.priceToBook || "30") <= 22.5 ? "green" : "red",
    },
    "Investor Suitability": {
      value: goodForDefensiveInvestor(stockData),
      description: "An overall assessment of the stock's suitability for Defensive investors.",
      color: goodForDefensiveInvestor(stockData) === "BAD" ? "red" : "green",
    },
});
  
export const getEnterprisingData = (stockData: Stock) => ({
    "Revenue": {
      value: (parseFloat(stockData.detail?.totalRevenue ?? "0")/1000000000).toFixed(2) + " B",
      description: "Revenue refers to the total income generated by the company from its business activities.",
      color: parseFloat(stockData.detail?.totalRevenue ?? "-1" ) > 0 ? "green" : "red",
    },
    "Current Ratio": {
      value: stockData.detail?.currentRatio ?? "N/A",
      description: "The current ratio measures the company's current assets against its current liabilities.",
      color: parseFloat(stockData.detail?.currentRatio ?? "0") >= 1.5 ? "green" : "red",
    },
    "Earnings Stability": {
      value: isEarningsStable(stockData.eps, 5) ? "Stable" : "Unstable",
      description: "This indicates whether the company's earnings per share have remained positive over the last 5 years.",
      color: isEarningsStable(stockData.eps, 5) ? "green" : "red",
    },
    "Dividend Record": {
      value: isDividendStable(stockData.dividends, 1) ? "Stable" : "Unstable",
      description: "A stable dividend record means the company has consistently paid dividends over the last year.",
      color: isDividendStable(stockData.dividends, 1) ? "green" : "red",
    },
    "Earnings Growth": {
      value: hasEarningsIncreased(stockData.eps, "enterprising") !== -1 ? hasEarningsIncreased(stockData.eps, "enterprising").toFixed(2) : "N/A",
      description: "The average growth of earnings per share compared to the initial years.",
      color: hasEarningsIncreased(stockData.eps, "enterprising") >= 1.0 ? "green" : "red",
    },
    "Price/Earnings Ratio": {
      value: threeYearsPeRatio(stockData.peRatio).toFixed(2),
      description: "The P/E ratio reflects the price of the stock compared to the company's earnings per share.",
      color: "green",
    },
    "Price/Assets Ratio": {
      value: priceToAssetRatio(stockData.peRatio, stockData.detail?.priceToBook || Infinity.toString()) !== Infinity ? priceToAssetRatio(stockData.peRatio, stockData.detail?.priceToBook || Infinity.toString()).toFixed(2) : "N/A",
      description: "This measures the ratio of the stock price to the book value of the company's assets.",
      color: priceToAssetRatio(stockData.peRatio, stockData.detail?.priceToBook || "20") <= 18.0 ? "green" : "red",
    },
    "Investor Suitability": {
      value: goodForEnterprisingInvestor(stockData),
      description: "An overall assessment of the stock's suitability for Enterprising investors.",
      color: goodForEnterprisingInvestor(stockData) === "BAD" ? "red" : "green",
    },
});