import { Stock } from "../../../types/Stock";
import { isEarningsStable, isDividendStable, hasEarningsIncreased, threeYearsPeRatio, priceToAssetRatio, goodForDefensiveInvestor, goodForEnterprisingInvestor } from "./benjaminGrahamUtils";

export const getDefensiveData = (stockData: Stock) => ({
    "Revenue": {
      value: stockData.detail?.totalRevenue,
      description: "Revenue refers to the total income generated by the company from its business activities.",
      color: parseFloat(stockData.detail?.totalRevenue) < 100000000 ? "red" : "green",
    },
    "Current Ratio": {
      value: stockData.detail?.currentRatio,
      description: "The current ratio measures the company's ability to pay short-term obligations with its short-term assets.",
      color: parseFloat(stockData.detail?.currentRatio) < 2 ? "red" : "green",
    },
    "Earnings Stability": {
      value: isEarningsStable(stockData.eps, 10),
      description: "This indicates whether the company's earnings have remained positive over the last 10 years.",
      color: isEarningsStable(stockData.eps, 10) === "BAD" ? "red" : "green",
    },
    "Dividend Record": {
      value: isDividendStable(stockData.dividends, 20),
      description: "A stable dividend record means the company has consistently paid dividends over the last 20 years.",
      color: isDividendStable(stockData.dividends, 20) === "BAD" ? "red" : "green",
    },
    "Earnings Growth": {
      value: hasEarningsIncreased(stockData.eps, "defensive"),
      description: "The average growth of earnings compared to the initial years.",
      color:
        hasEarningsIncreased(stockData.eps, "defensive") === "N/A" ||
        parseFloat(hasEarningsIncreased(stockData.eps, "defensive")) > 4.0 / 3
          ? "red"
          : "green",
    },
    "Price/Earnings Ratio": {
      value: threeYearsPeRatio(stockData.peRatio),
      description: "The P/E ratio reflects the company's valuation based on its earnings for the last few years.",
      color:
        threeYearsPeRatio(stockData.peRatio) === "N/A" ||
        parseFloat(threeYearsPeRatio(stockData.peRatio)) > 15.0
          ? "red"
          : "green",
    },
    "Price/Assets Ratio": {
      value: priceToAssetRatio(stockData.peRatio, stockData.detail?.priceToBook),
      description: "This measures the ratio of the stock price to the book value of the company's assets.",
      color:
        priceToAssetRatio(stockData.peRatio, stockData.detail?.priceToBook) === "N/A" ||
        parseFloat(priceToAssetRatio(stockData.peRatio, stockData.detail?.priceToBook)) > 22.5
          ? "red"
          : "green",
    },
    "Investor Suitability": {
      value: goodForDefensiveInvestor(stockData),
      description: "An overall assessment of the stock's suitability for Defensive investors.",
      color: goodForDefensiveInvestor(stockData) === "BAD" ? "red" : "green",
    },
});
  
export const getEnterprisingData = (stockData: Stock) => ({
    "Revenue": {
      value: stockData.detail?.totalRevenue,
      description: "Revenue refers to the total income generated by the company from its business activities.",
      color: parseFloat(stockData.detail?.totalRevenue) <= 0 ? "red" : "green",
    },
    "Current Ratio": {
      value: stockData.detail?.currentRatio,
      description: "The current ratio measures the company's ability to pay short-term obligations with its short-term assets.",
      color: parseFloat(stockData.detail?.currentRatio) < 1.5 ? "red" : "green",
    },
    "Earnings Stability": {
      value: isEarningsStable(stockData.eps, 5),
      description: "This indicates whether the company's earnings have remained positive over the last 5 years.",
      color: isEarningsStable(stockData.eps, 5) === "BAD" ? "red" : "green",
    },
    "Dividend Record": {
      value: isDividendStable(stockData.dividends, 1),
      description: "A stable dividend record means the company has consistently paid dividends over the last year.",
      color: isDividendStable(stockData.dividends, 1) === "BAD" ? "red" : "green",
    },
    "Earnings Growth": {
      value: hasEarningsIncreased(stockData.eps, "enterprising"),
      description: "The average growth of earnings compared to the initial years.",
      color:
        hasEarningsIncreased(stockData.eps, "enterprising") === "N/A" ||
        parseFloat(hasEarningsIncreased(stockData.eps, "enterprising")) <= 1
          ? "red"
          : "green",
    },
    "Price/Earnings Ratio": {
      value: stockData?.peRatio?.sort((a, b) => b.Year - a.Year)[0].PE_Ratio,
      description: "The P/E ratio reflects the company's valuation based on its earnings for the last few years.",
      color: "green",
    },
    "Price/Assets Ratio": {
      value: priceToAssetRatio(stockData.peRatio, stockData.detail?.priceToBook),
      description: "This measures the ratio of the stock price to the book value of the company's assets.",
      color: (stockData.detail?.priceToBook === null || parseFloat(stockData.detail?.priceToBook) < 1.2)
          ? "red"
          : "green",
    },
    "Investor Suitability": {
      value: goodForEnterprisingInvestor(stockData),
      description: "An overall assessment of the stock's suitability for Enterprising investors.",
      color: goodForEnterprisingInvestor(stockData) === "BAD" ? "red" : "green",
    },
});