name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/yarn
            ./Laba/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('./Laba/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: ./Laba/yarn.lock
          node-version: 20.x
          cache: 'yarn'

      - run: yarn install
        working-directory: ./Laba

      - run: yarn build
        working-directory: ./Laba

      - run: yarn test
        working-directory: ./Laba
